version = "1.0"

[main]
name = "Nextcloud configuration"

    [main.mode]
    name = "Modes"

        [main.mode.maintenance_mode]
        ask = "Enable maintenance mode"
        type = "boolean"
        default = "0"
        
        [main.mode.closed_network_mode]
        ask = "Enable closed network mode"
        type = "boolean"
        default = "0"
        help = "Is Nextcloud connected to the Internet or running in a closed network?"

    [main.localization]
    name = "Localization"

        [main.localization.default_phone_region]
        ask = "Default phone region"
        type = "select"
        default = "0"
        help = "It is required to allow inserting phone numbers in the user profiles starting without the country code (e.g. +49 for Germany)."

        [main.localization.default_timezone]
        ask = "Default timezone"
        type = "select"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "Europe/Paris"
        help = "The default timezone parameter is only used when the timezone of the user can’t be determined."

    [main.account]
    name = "Account"

        [main.account.lost_password_link]
        ask = "Lost password link"
        type = "url"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "0"
        help = "Allow to redirect on a custom form to require a password reset (for example to ask you to reset it from this yunohost webadmin)"
        
        [main.account.logout_url]
        ask = "Logout URL"
        type = "url"
        bind = ":__INSTALL_DIR__/config/config.php"
        help = "Redirect on this URL when a user click on 'Logout' action"

    [main.files]
    name = "Files"
        
        [main.account.trashbin_retention_obligation]
        ask = "Trashbin retention"
        type = "string"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "auto"
        help = "If the trash bin app is enabled (default), this setting defines the policy for when files and folders in the trash bin will be permanently deleted."

        [main.account.version_retention_obligation]
        ask = "Version retention"
        type = "string"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "auto"
        help = "If the versions app is enabled (default), this setting defines the policy for when versions will be permanently deleted."

        [main.account.enable_previews]
        ask = "Enable previews"
        type = "boolean"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "1"
        help = "Info: Previews of photos and text documents could consume a lot of resources."

    [main.apps]
    name = "Apps"
        
        [main.account.auto_update]
        ask = "Auto update apps"
        type = "boolean"
        default = "1"
        help = "Automatically update apps each night"
        
        [main.apps.defaultapp]
        ask = "Default app to display"
        type = "tags"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "dashboard,files"
        help = "Set the default app to open on login."

        [main.apps.appsallowlist]
        ask = "List of apps installable"
        type = "tags"
        bind = ":__INSTALL_DIR__/config/config.php"
        default = "all"
        help = "Filters allowed installable apps from the appstore."


    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.fpm_footprint]
        ask = "Memory footprint"
        type = "select"
        choices.low = "Low, <= 20Mb per pool"
        choices.medium = "Medium, between 20Mb and 40Mb per pool"
        choices.high = "High, > 40Mb per pool"
        choices.specific = "Use specific value"
        default = "low"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific'"
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        ask = "Expected usage"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
