test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c5cf91ad.name = "Upgrade from 25.0.2"
    test_upgrade_from.d02166a5.name = "Upgrade from 26.0.1"
    test_upgrade_from.0f16f720.name = "Upgrade from 27.0.2"
    


